OK  = 'OK'
NOK = 'NOK'
MESSAGE = 'message'
STATUS  = 'status'
GEOCOODING_URL_PREFIX = 'https://maps.googleapis.com/maps/api/geocode/json?latlng='
SERVER_API_KEY = 'AIzaSyCmb-8YiYsK52VuJPV4ZKwiq4rVjsqnUZs'